### ISSUE TITLE
Versioning outputs

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#72]

**Comment by leifdenby** [comment]
My proposal for versioning is:

- version **both** trajectories and forcings in the same way
- user optionally able to specify a version in the yaml-file(s) (that describe how to create a given trajectory or forcing) using the `version` attribute
- if the `version` attribute hasn't been set we use the default value `unversioned`
- the `version` variable is used in both the filename (`{trajectory_name}.v{version}.nc`) and set in the netCDF attribute `version`
- if a file already exists with the output filename (for example the user is running the creation of a trajectory `eurec4a_010220` and hasn't set the `version` attribute in the yaml file, and so the output file would be `eurec4a_010220.unversioned.nc` and the user is running trajectory creation a second time) we don't overwrite the file but instead stop the trajectory creation, informing the user to either 1) delete the file to re-create it or 2) set/change the `version` attribute in the yaml file to create a new trajectory.
- we copy all attributes in the yaml-file to global attributes in the netCDF file. This ensures that we know what the creation attributes were in the case where the input yaml-file change over time
- when creating a forcing from a trajectory we copy over all global attributes from the trajectory prefixing each with `trajectory_`, e.g. `trajectory_gradient_method`. Similarly when creating a trajectory from a domain we copy over all global attributes prefixed with `domain_` for example `domain_source` (which would become `trajectory_domain_source` in a forcing netCDF file`).
- we change all input definition yaml-files that we include with lagtraj to include the attribute `version: 1`. This will also ensure that you and I know what versions of the domain/trajectory/forcing definitions we are working with is clear
- we add the version of lagtraj as a global variable to all netCDF files written by lagtraj. This is based on versioneer so that it is `{git-version-tag}.{git-commit}` so that we know which commit is referred to and includes the postfix `-dirty` if someone has modified lagtraj since the last commit (this will help with debugging differences between files created from committed and modified versions of lagtraj)

What are your thoughts on this @sjboeing? I think this ensures that all information about how output is created is saved and we avoid creating trajectories and forcings which are inconsistent with what we assume.

**Comment by sjboeing** [comment]
This sounds good @leifdenby . It may seem a bit of an overkill, but I think it will help us trace issues. One thing to note is that DEPHY SCM files are usually named "$CASE$_$SUBCASE$_SCM_driver.nc". I have not implemented this filename convention at this point, we may want to use $name_$version_SCM_driver.nc for DEPHY output but the file names become a bit tedious that way.
