### ISSUE TITLE
Suggestions for changes to forcing conversions functionality

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#73]
I have a few suggestions about how to change the routines for converting the forcings, I would:

1. Move the `lagtraj.conversions` module to `lagtraj.forcing.convert` as the forcing is related explicitly to changing a forcing file and not to changing domain data or trajectories

2. Move the functionality that refers to `hightune` or `racmo` in the `era5` module to the `hightune` and `racmo` modules, and rename the remaining `era5` module as `main`. As the variable naming conventions that we use throughout lagtraj are the ERA5 format I think we don't need to have a module that refers to ERA5, with a module `era5` it might give the impression that we can convert *to* ERA5, rather than from.

3. I like the idea of being able to run `lagtraj.forcing.create` with an optional flag `--output-format`. Is the idea that would refer to a specific yaml-file that defines output for a given target system (e.g. `racmo`)? Could we let the standard format be called `era5` rather than `dummy_netcdf`?

4. Move yaml-files for conversion of forcings to `input_examples/forcings/conversion`

What do you think @sjboeing?

**Comment by sjboeing** [comment]
Hi @leifdenby, 

Thanks for looking at the code in more detail. I will try to finish the HIGH-TUNE format first, but then we can think about moving things around a bit. Some thoughts:
** So far we have been using era5 indeed, but I hope eventually the code will be generalised to other inputs (e.g. dropsondes, UM, ICON), so the conversions are from an input format to an output format, although there could be a master conversion python file where the input format is determined. 
**I have placed most of the dictionaries etc. that depend on both (input and output) with the input format rather than the output format, which is where they will be used (if they are placed there, they do not need to be imported). The dictionaries that are generic to the output format are in a file named after the output format.
** The conversion may go beyond simply a translation, and it can have its own parameters (like the nudging time, any regridding, and other changes like the skin temperature change). In other words: we will likely end up with multiple era5_to_racmo and era5_to_hightune yaml files. So rather than --output-format we could have e.g. a --conversion-file flag. I like the ability to run the conversion on its own, but in principle it could be placed under forcings. One reason to not do this, is that the the directory structure becomes deeper (I tend to prefer a flatter structure for navigation and searching, in order to find things I tend to end up grepping, e.g. "grep dummy_netcdf *.py */*.py */*/*.py */*/*/*.py")
** Could we let the standard format be called era5 rather than dummy_netcdf? -> Good idea!

**Comment by sjboeing** [comment]
I was just thinking a bit more about the conversion yaml files. There is something to be said for putting as many parameters as we can in the conversion yaml (effectively any parameters that do not require recalculation of the forcings in native format, like the ones relating to nudging and whether to used radiative tendencies or the radiation scheme), rather than the forcing yaml. This would mean the forcings don't need to be recalculated unless strictly neccesary. There are also some metadata parameters which may be better added at the trajectory level. Would be good to have a quick call about this sometime next week.

**Comment by sjboeing** [comment]
@leifdenby: are you happy to close this issue?
